backup_root       = r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Hidromod\2025\Proj_575_Consulgal_Soyo\Aplica\MOHID_Water\run_cases\Soyo\backup'
hdf5_file         =r'WaterProperties_2.hdf5'
hdf5_file_vectors =r'Hydrodynamic_2.hdf5'
figures_folder    = r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Postprocessing\out\vertical_cut'
csv_file          = r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Postprocessing\work\Plot_Vertical_Cut\VerticalCutPath.csv'
start_date_str    = '2025-1-6'
end_date_str      = '2025-1-7'
variable          = 'salinity'
label             = 'Salinity(psu)'
variable_vector   = ['velocity U', 'velocity V']
show_vectors      = True
save_frames       = True
skip_time         = 1
extent_cells      = 1
increase_zoom_level = 1
transparency_factor = 1.0
dpi               = 150
cmap              = 'jet'
skip_vector       = 5
vector_scale      = 10
vector_color      = 'white'
