backup_root       = r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Postprocessing\res'
hdf5_file         =r'Hydrodynamic_2_Surface.hdf5'
hdf5_file_vectors=r'Hydrodynamic_2_Surface.hdf5'
figures_folder    = r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Postprocessing\out\maps'
start_date_str    = '2025-9-25'
end_date_str      = '2025-9-27'
variable          = 'velocity modulus'
label             = 'Velocity Modulus(m/s)'
variable_vector   = ['velocity U', 'velocity V']
show_vectors      = True
save_frames       = True
skip_time         = 3
extent_cells      = 1
increase_zoom_level = 1
skip_vector       = 5
vector_scale      = 10
vector_color      = 'white'
transparency_factor = 1.0
dpi               = 150
cmap               = 'jet'
