backup_root       = r'C:\Users\aquaf\OneDrive\MOHID_Jupyter-Notebooks-master\MOHID_Jupyter-Notebooks-master\MOHID_Water\run_cases\Coastal3D_Operational\backup\ERA5'
figures_folder    = r'C:\Users\aquaf\OneDrive\MOHID_Jupyter-Notebooks-master\MOHID_Jupyter-Notebooks-master\MOHID_Water\run_cases\Coastal3D_Operational\backup\ERA5\figures'
hdf5_file         =r'Meteo.hdf5'
hdf5_file_vectors=r'Meteo.hdf5'
start_date_str    = '2025-1-1'
end_date_str      = '2025-1-6'
variable          = 'wind velocity'
label             = 'Wind Velocity(m/s)'
variable_vector   = ['wind velocity X', 'wind velocity Y']
show_vectors      = True
save_frames       = True
skip_time         = 3
extent_cells      = 1
increase_zoom_level = 1
skip_vector       = 1
vector_scale      = 250
vector_color      = 'white'
transparency_factor = 0.5
dpi               = 150
cmap               = 'jet'
