dir_path=r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Water\run_cases\Coastal3D_Operational\backup\ERA5//20250106_20250107'
hdf5_file=r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Water\run_cases\Coastal3D_Operational\backup\ERA5//20250106_20250107\Meteo.hdf5'
hdf5_file_vectors=r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Water\run_cases\Coastal3D_Operational\backup\ERA5//20250106_20250107\Meteo.hdf5'
variable='air temperature'
label='Temperature(°C)'
variable_vector=['wind velocity X', 'wind velocity Y']
show_vectors=True
save_frames=True
skip_time=3
extent_cells=1
increase_zoom_level=1
skip_vector=1
vector_scale=250
vector_color='white'
transparency_factor=0.5
dpi=150
