name: MOHID_Water_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - cdsapi
  - contextily
  - copernicusmarine
  - folium
  - h5py
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - netcdf4
  - notebook
  - numpy
  - pandas
  - requests
  - tqdm
  - xarray
  - cartopy
  - scipy
  - imageio-ffmpeg
  - dash
  - geoglows
