backup_root       = r'D:\Aplica\Proj_575_Consulgal_Soyo\Aplica\MOHID_Water\run_cases\Soyo\backup\Level_3'
hdf5_file_vectors=r'Hydrodynamic_2.hdf5'
out_dir           = r'D:\Aplica\Proj_575_Consulgal_Soyo\Aplica\MOHID_Water\run_cases\Soyo\Figures\Level_3_40m\MOHID_Postprocessing\out\residual'
start_date_str    = '2025-1-17'
end_date_str      = '2025-2-1'
label             = 'Mean Velocity (m/s)'
countour_levels   = []
vmin              = 0.0
vmax              = 0.1
mean_map          = 'surface'
nlayer            = 9
extent_cells      = 1
increase_zoom_level = 3
transparency_factor = 1.0
dpi               = 150
cmap              = 'jet'
skip_vector       = 3
vector_scale      = 1
vector_color      = 'white'
variable_vector   = ['velocity U', 'velocity V']
title             = 'Mean velocity at bottom sigma layer'
extent             = None
shapefile_path     = r'None'
shapefile_color     = 'black'
shapefile_transparency_factor     = 0.5
fontsize_label     = 20
fontsize_title     = 18
fontsize_tick     = 20
