backup_root       = r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Postprocessing\res'
hdf5_file         =r'Hydrodynamic_2_Surface.hdf5'
hdf5_file_vectors=r'Hydrodynamic_2_Surface.hdf5'
out_dir           = r'C:\Users\aquaf\OneDrive\Projetos\Aquaflow\Maretec\Jupyter Notebooks\MOHID_Postprocessing\out\statistics'
start_date_str    = '2025-9-25'
end_date_str      = '2025-9-27'
variable          = 'velocity modulus'
label             = 'Velocity Modulus(m/s)'
percentil         = 50
countour_levels   = []
vmin              = 0.0
vmax              = 1.0
percentil_map     = 'surface'
nlayer            = 1
extent_cells      = 1
increase_zoom_level = 1
transparency_factor = 1.0
dpi               = 150
cmap              = 'jet'
skip_vector       = 5
vector_scale      = 10
vector_color      = 'white'
variable_vector   = ['velocity U', 'velocity V']
show_vectors      = True
