name: MOHID_Preprocessing_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - ipython
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - scipy
  - cartopy
  - pillow
  - geopandas
  - shapely
  - requests