name: MOHID_Lagrangian_environment
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.2.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.14
  - aiosignal=1.3.2
  - annotated-types=0.6.0
  - anyio=4.9.0
  - aom=3.9.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asciitree=0.3.3
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - boto3=1.36.3
  - botocore=1.36.3
  - bottleneck=1.4.2
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cartopy=0.24.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - cftime=1.6.4
  - charset-normalizer=3.4.1
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - copernicusmarine=2.0.1
  - cpython=3.13.2
  - cycler=0.12.1
  - dash=3.0.0
  - dask-core=2025.2.0
  - dav1d=1.2.1
  - debugpy=1.8.13
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - double-conversion=3.3.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fasteners=0.16.3
  - ffmpeg=7.1.1
  - flask=3.1.0
  - folium=0.19.5
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gdk-pixbuf=2.42.12
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.0
  - geotiff=1.7.4
  - gl2ps=1.4.2
  - glew=2.1.0
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.2.0
  - h5netcdf=1.6.1
  - h5py=3.12.1
  - harfbuzz=10.4.0
  - hdf4=4.2.15
  - hdf5=1.14.4
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipyleaflet=0.19.2
  - ipython=9.0.2
  - ipython_genutils=0.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.4.2
  - json5=0.10.0
  - jsoncpp=1.9.6
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=7.4.9
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_leaflet=0.19.2
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.1
  - libcurl=8.12.1
  - libde265=1.0.15
  - libdeflate=1.22
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgdal-core=3.10.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libheif=1.18.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libmpdec=4.0.0
  - libnetcdf=4.9.2
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.47
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libusb=1.0.28
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.6
  - libxslt=1.1.41
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - locket=1.0.0
  - loguru=0.7.2
  - lxml=5.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - mistune=3.1.3
  - mkl=2024.2.2
  - msgpack-python=1.0.3
  - multidict=6.2.0
  - munkres=1.1.4
  - narwhals=1.31.0
  - nbclassic=1.2.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - numba=0.61.0
  - numcodecs=0.15.1
  - numexpr=2.10.2
  - numpy=2.1.3
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openssl=3.4.1
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=3.6.4
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - plotly=5.15.0
  - proj=9.5.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - propcache=0.2.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pugixml=1.14
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pyogrio=0.10.0
  - pyparsing=3.2.2
  - pyproj=3.7.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pystac=1.12.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2025.1
  - pywin32=307
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.3.0
  - qhull=2020.2
  - qt6-main=6.8.2
  - rav1e=0.6.6
  - referencing=0.36.2
  - requests=2.32.3
  - retrying=1.3.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.23.1
  - s3transfer=0.11.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdl2=2.32.50
  - sdl3=3.2.8
  - semver=3.0.2
  - send2trash=1.8.3
  - setuptools=75.8.2
  - shapely=2.0.7
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.49.1
  - stack_data=0.6.3
  - stringcase=1.2.0
  - svt-av1=3.0.1
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - tenacity=9.0.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.3.0
  - utfcpp=4.0.6
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - vtk=9.3.1
  - vtk-base=9.3.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - widgetsnbextension=4.0.13
  - win32_setctime=1.2.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.17.2
  - wslink=2.3.3
  - x264=1!164.3095
  - x265=3.5
  - xarray=2024.11.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.1.0
  - xz=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - yarl=1.18.3
  - zarr=2.18.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - jupyter-contrib-core==0.4.2
      - jupyter-nbextensions-configurator==0.6.4
